app/routes.py
import os
from flask import request, render_template, url_for, redirect, Blueprint
import requests


from .methods import *
from .forms import *

# TODO: When you click on a book, it should take you to the ebook.

main = Blueprint("main", __name__)


@main.route("/", methods=["GET"])
def welcome():
    # TODO: Sorted by their ratings, show the top 3 or 4 books on the homepage before the buttons

    return render_template("index.html")

@main.route("/home/")
def home():
    button_pressed = request.args.get("button")
    books = []
    if button_pressed == "completed":
        books = get_completed_books()
    elif button_pressed == "ongoing":
        books = get_ongoing_books()
    elif button_pressed == "no_comment":
        books = get_disliked_books()
    elif button_pressed == "all_books":
        books = get_all_books()
    # else:
    #     return redirect(url_for("main.welcome"))
    return render_template("home.html", books=books)
    # return "Hi"

@main.route("/add", methods=["GET", "POST"])
def add_book():
    # TODO: Since the google API is acting weird, add another button for the user to add the books themselves.
    #       They don't need to have all the fields, just the important ones. Create a new form for this.
    #       They might need to upload image files though.
    form = AddNewBookForm()
    redirected = request.args.get("redirected")
    if form.user_add.data:
        return redirect(url_for("main.user_add_book"))
    if form.cancel.data:
        return redirect(url_for("main.welcome"))
    if form.validate_on_submit():
        if form.api_add.data:
            title = form.title.data
            author = form.author.data
            query = {"intitle": title,
                     "inauthor": author}
            return redirect(url_for("main.select_book", query=query))

    return render_template("add.html", form=form, redirected=redirected)

@main.route("/input", methods=["GET", "POST"])
def user_add_book():
    edit_true = False
    form = EditBookForm()
    if form.validate_on_submit():
        if form.submit.data:
            new_data = {field.name: field.data for field in form if form.data}
            print(new_data)
            add_new_book(new_data, user_added=True)
            return redirect(url_for("main.welcome"))
        elif form.cancel.data:
            # Add flash
            return redirect(url_for("main.welcome"))
    return render_template("edit.html", form=form, edit_true=edit_true)

@main.route("/select_book")
def select_book():
    """Select which book you'd like added to the database."""
    # TODO: Find a way to incorporate books later. Use this tag:
    #  <img src="{{book['imageLinks']['medium']}}" class="d-block user-select-none" width="100%" height="200" alt="{{book.title}} book cover image">
    query = request.args.get("query")
    GOOGLE_BOOKS_API_KEY = os.environ.get("GOOGLE_BOOKS_API_KEY")
    VOLUME_FIND_URL = f"https://www.googleapis.com/books/v1/volumes?q={query}&key={GOOGLE_BOOKS_API_KEY}"
    try:
        response = requests.get(url=VOLUME_FIND_URL)
        response.raise_for_status()
    except requests.exceptions.RequestException as error:
        # TODO: Create a custom error page that the user will be redirected to. They will have the option to go back to
        #  the home page from that error page.
        pass

    else:
        results = response.json()
        all_books = results["items"]
        return render_template("select.html", all_books=all_books)

@main.route("/add_to_database")
def add_to_database():
    volume_id = request.args.get("volume_id")[1:]
    # TODO: Rewrite code. The link to the book can be found in the json for the volume api
    BOOK_DETAILS_URL = f"https://www.googleapis.com/books/v1/volumes/{volume_id}"
    try:
        response = requests.get(BOOK_DETAILS_URL)
        response.raise_for_status()
    except requests.exceptions.HTTPError as error:
        # TODO: Create a custom error page that the user will be redirected to. They will have the option to go back to
        #  the home page from that error page.
        if response.status_code:
            print(response.json())
            redirected = True
            return redirect(url_for("main.add_book", redirected=redirected))
    else:
        results = response.json()
        print(results)
        book_fields = {"title": results["volumeInfo"]["title"],
                       "author": results["volumeInfo"]["authors"][0],
                       "isbn": results["volumeInfo"]["industryIdentifiers"][1]["identifier"],
                       "number_of_pages": results["volumeInfo"]["pageCount"],
                       "cover_image": results["volumeInfo"]["imageLinks"]["medium"],
                       "synopsis": results["volumeInfo"]["description"]
                       }
        book_id = add_new_book(book_fields=book_fields)
        return redirect(url_for("main.edit", book_id=book_id))

@main.route("/edit", methods=["GET", "POST"])
def edit():
    edit_true = True
    book_id = request.args.get("book_id")
    book = db.session.execute(db.select(Books).where(Books.id == book_id)).scalar()
    print(book)
    form = EditBookForm(obj=book)
    book_to_edit = db.session.execute(db.select(Books).where(Books.id == book_id)).scalar()
    if form.validate_on_submit():
        if form.submit.data:
            new_data = {field.name: field.data for field in form if form.data}
            print(new_data)
            edit_book(book_id=book_id, new_data=new_data)
            return redirect(url_for("main.welcome"))
        elif form.cancel.data:
            return redirect(url_for("main.welcome"))
    return render_template("edit.html", form=form, book_to_edit=book_to_edit, edit_true=edit_true)

@main.route("/delete")
def delete():
    # TODO: Add a page/condition that checks if the user is sure they want to delete the book in question.
    # TODO: Do not actually delete the record, figure out a better way to deal with this.
    book_id = request.args.get("book_id")
    delete_book(book_id=book_id)
    return redirect(url_for("main.home"))

@main.route("/view_book/")
def view_book():
    return "<h1>This page is not ready</h1>"

@main.route("/search")
def search():
    # Think about only getting the data from base.html. Research more on this.
    return "<h1>This page is not ready</h1>"

app/templates/add.html
{% extends 'base.html' %}
{% from 'bootstrap5/form.html' import render_form %}

{% block title %}Add New Book{% endblock %}

{% block content %}
<div class="content">
    {% if redirected %}
    <div class="alert alert-dismissible alert-primary" style="margin-bottom: 30px">
        <button type="button" class="btn-close" data-bs-dismiss="alert" fdprocessedid="fpk3vw"></button>
        <strong>Oh snap! </strong>There seems to be a server issue. Book could not be added, try again.
    </div>
    {% endif %}
    <h1 class="heading">Add a New Book</h1>
    {{ render_form(form, novalidate=True,) }}
</div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en" style="margin-bottom: 30px">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{url_for('main.welcome')}}">My Library</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01"
            aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" href="{{ url_for('main.home') }}">All Books
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.add_book') }}">Add Book</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-sm-2" type="search" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

    {% block styles %}

    <!-- Load Bootstrap-Flask CSS here -->
    {{ bootstrap.load_css() }}
    <!-- Link to the styles.css here to apply styling to all the child templates.-->
    {% endblock %}
    <title>
      {% block title %}{% endblock %}
    </title>
  </head>
  <body>
    {% block content %}{% endblock %}

    {% block scripts %}
    <!-- Optional JavaScript -->
    {{ bootstrap.load_js() }}
    {% endblock %}
  </body>
</html>

app/templates/edit.html
{% extends 'base.html' %}
{% from 'bootstrap5/form.html' import render_form %}

{% block title %}Edit Book{% endblock %}

{% block content %}
<div class="content">
  {% if edit_true %}
  <h1 class="heading">Edit {{ book_to_edit.title }}</h1>
  <p class="description">Which fields would you like to change?</p>
  {% else %}
  <h1 class="heading">Input New Book Details</h1>
  <p class="description">Please fill in the fields</p>
  {% endif %}

<!--    think about adding the current data for the fields so the user knows what to expect-->
    {{ render_form(form, novalidate=True) }}
  </div>
{% endblock %}

app/templates/home.html
{% extends 'base.html' %}

{% block title %}My Personal Library{% endblock %}

{% block content %}

<div class="container">
  <h1 class="heading" align="center" style="margin-top: 20px; margin-bottom: 20px">Welcome to my library</h1>
  <p class="description" align="center" style="margin-bottom: 30px">These are all the books that have captured my attention... and my heart. Some are good,
      others are really good, and a few.....well all I can say for those is, "We listen, we don't judge. Depending on
      which option you chose, you can enjoy your fill, or well suffer the consequences."</p>
</div>

<div class="container row-cols-4 ">
    {% for book in books %}

    <a href="{{ url_for('main.view_book') }}">
    <div class = "col">
        <div class="card mb-3">
            <img src="{{book.cover_image}}" class="d-block user-select-none" width="100%" height="400" alt="{{book.title}} book cover image">
            <div class="card-body">
                <p class="card-text">{{book.title}}</p>
            </div>
            <div class="card-body row" style="align: center">
                <div class="col"><a href="{{ url_for('main.view_book') }}" class="card-link">View Book</a></div>
                <div class="col"><a href="{{ url_for('main.edit', book_id=book.id) }}" class="card-link">Update Details</a></div>
                <div class="col"><a href="{{ url_for('main.delete', book_id=book.id) }}" class="card-link">Delete Book</a></div>
            </div>
        </div>
    </div>
    </a>
    {% endfor %}
</div>



<div class="container text-center add">
<a href="{{ url_for('main.add_book') }}" class="button">Add New Book</a>
</div>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block title %}My Personal Library{% endblock %}

{% block content %}

<div class="container">
  <h1 align="center" style="margin-top: 20px; margin-bottom: 20px">Welcome to my library</h1>
  <p align="center" style="margin-bottom: 30px">These are all the books that have captured my attention... and my heart. Some are good,
      others are really good, and a few.....well all I can say for those is, "We listen, we don't judge. Depending on
      which option you chose, you can enjoy your fill, or well suffer the consequences."</p>
</div>

<figure style="margin-bottom: 70px">
  <blockquote class="blockquote">
    <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>

  </blockquote>
  <figcaption class="blockquote-footer">
    Someone famous in <cite title="Source Title">Source Title</cite>
  </figcaption>x
</figure>

<div align="center ">
    <form action="{{url_for('main.home')}}" method="GET">
        <div class="row" style="margin: 30px">
            <div class="col-4"><button type="submit" name="button" value="completed" class="btn btn-primary" style="width: 400px">COMPLETED BOOKS</button></div>
            <div class="col-4"><button type="submit" name="button" value="ongoing" class="btn btn-primary" style="width: 400px">ONGOING BOOKS</button></div>
            <div class="col-4"><button type="submit" name="button" value="no_comment" class="btn btn-primary" style="width: 400px">WE WILL NEVER SPEAK OF THESE AGAIN</button></div>

        </div>
        <button type="submit" name="button" value="all_books" class="btn btn-primary btn-lg col-6">SHOW ME ALL BOOKS</button>
    </form>
</div>

{% endblock %}

app/templates/select.html
{% extends 'base.html' %}

{% block title %}Select Book{% endblock %}

{% block content %}
<div class="container card-flex row-cols-4">
    <h1 class="heading">Select Book</h1>
    {% for book in all_books %}
    <a href="{{ url_for('main.add_to_database', volume_id=book['id']) }}">
        <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
            <div class="card-header">PUT BOOK COVER IMAGE</div>
                <div class="card-body">
                    <h4 class="card-title">{{ book["volumeInfo"]["title"] }}</h4>
                    <p class="card-text">{{ " ".join(book["volumeInfo"]["authors"]) }}</p>
                </div>
        </div>
    </a>
    {% endfor %}
</div>
{% endblock %}